AdminServer:
  ports:
  - ${admin_port}:${admin_port}/tcp
  environment:
    AdminPort: ${admin_port}
    Server_Role: Admin
    base_domain_default_password: ${weblogic_password}
  labels:
    io.rancher.scheduler.affinity:host_label: AdminServer=True
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  tty: true
  image: alanpeng/oracle-weblogic11g-cluster:1036
  volumes:
  - /root/WebLogic/user_projects:/root/Oracle/Middleware/user_projects
ManagedServer:
  ports:
  - ${managed_port}:7001/tcp
  environment:
    AdminPort: ${admin_port}
    Server_Role: Managed
    base_domain_default_password: ${weblogic_password}
  labels:
    io.rancher.scheduler.affinity:host_label: ManagedServer=True
    io.rancher.container.hostname_override: container_name
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
  tty: true
  image: alanpeng/oracle-weblogic11g-cluster:1036
  stdin_open: true
